version: '3.9'

services:
  symfony-php:
    container_name: symfony-php
    build:
      context: ../.
      dockerfile: dockerPhp.Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ../Configs/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ../Configs/php.ini:/usr/local/etc/php/conf.d/php-additional.ini
      - ../../:/var/www
      
  symfony-nginx:
    image: nginx:latest
    container_name: symfony-nginx
    ports:
      - 443:443
    volumes:
      - ../../:/var/www
      - ../Certs:/etc/nginx/certs
      - ../Configs/nginx.conf:/etc/nginx/nginx.conf
      - ../Configs/default.conf:/etc/nginx/conf.d/www.conf
      
  symfony-postgres:
    image: library/postgres:14.7
    container_name: symfony-postgres
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "root"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 54320:5432
    volumes:
      - postgres_data11:/var/lib/postgresql/data11
      
volumes:
  postgres_data11: {}